### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by demiros** [demiros/softuni_team_publich#1]
Software Requirement Specification should be created, and the good news are that it's almost one by Toni. The reason it's not uploaded here now is that Now is the starting of the github part of the project. 
SRS will  reside in /docs branch of the project.

**Comment by demiros** [comment]
SRS is uploaded by Toni. .docx file. it will be converted to .md and moved in /docs as the structure desciption.

**Comment by antoniapavlova** [comment]
Successfuly uploaded SRS_Message board system_Pablich Team.docx
