### ISSUE TITLE
The system should accept 5 symbols username for valid 

### ISSUE THREAD

**Issue by antoniapavlova** [demiros/softuni_team_publich#10]
Steps:
1) Go to http://palachinka.bg/msg-board/
2) Click Register link
3) Enter 5 symbols for username: "poiuy"
4) Enter password: "poiuy"

Expected result: The system should accept the username as valid.

Actual result: There is an alert message "Потребителското име трябва да е минимум 5 символа!"

**Comment by demiros** [comment]
Resolved!
